model: BPR

# Model configs
embedding_size: 16


# Training Settings
val_interval:
    rating: "[0, inf)"

epochs: 20
train_batch_size: 4096
learner: adam
learning_rate: 0.001
    # time: "[956703932, inf)"
train_neg_sample_args:
    distribution: uniform
    sample_num: 1

stopping_step: 5
# clip_grad_norm: 0.1
loss_decimal_place: 5
# weight_dacay: 0.1