# Environment Setting
gpu_id: 0
worker: 8
seed: 42
state: "INFO"
show_progress: True

# Data Settings
# dataset: ml-1m
data_path: /opt/ml/final-project-level2-recsys-11/dataset/

field_separator: "\t"
seq_separator: " "

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp

load_col:
    inter: [user_id, item_id, rating, timestamp]
    user: ['user_id', 'age', 'gender', 'occupation']
    item: ['item_id', 'release_year', 'class']
normalize_all: True

# General Train Settings
learner: adam
learning_rate: 0.001

train_neg_sample_args:
    distribution: uniform
    sample_num: 1

val_interval:
    rating: "[0, inf)"

# Evaluation Settings
eval_args:
    split: 
        LS: valid_and_test
    group_by: user
    order: TO
    mode: full # uni200, pop100 쓰면 100개중 추천
repeatable: False
metrics: 
    - Recall
    - Hit
    - Precision
    - NDCG
topk: 10
valid_metric: Recall@10

eval_step: 1
stopping_step: 5
eval_batch_size: 65536

# wandb_project: 'yang-bpr'
# log_wandb: True